services:
  - type: web
    name: oxoke-downloader-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_KEY
        value: oxoke_dl_admin_2025
